// <auto-generated />
using System;
using JecaInsurance.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JecaInsurance.API.Migrations
{
    [DbContext(typeof(JecaInsuranceDbContext))]
    partial class JecaInsuranceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JecaInsurance.API.Models.AnnuityQuote", b =>
                {
                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("QuoteId");

                    b.ToTable("AnnuityQuotes");
                });

            modelBuilder.Entity("JecaInsurance.API.Models.AutoQuote", b =>
                {
                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("QuoteId");

                    b.ToTable("AutoQuotes");
                });

            modelBuilder.Entity("JecaInsurance.API.Models.BOPQuote", b =>
                {
                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BusinessDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("QuoteId");

                    b.ToTable("BOPQuotes");
                });

            modelBuilder.Entity("JecaInsurance.API.Models.BoatQuote", b =>
                {
                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("QuoteId");

                    b.ToTable("BoatQuotes");
                });

            modelBuilder.Entity("JecaInsurance.API.Models.BusinessQuote", b =>
                {
                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnnualRevenue")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BusinessDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("BusinessOwnersPackage")
                        .HasColumnType("bit");

                    b.Property<bool>("CommercialAuto")
                        .HasColumnType("bit");

                    b.Property<bool>("CommercialCrime")
                        .HasColumnType("bit");

                    b.Property<bool>("CommercialProperty")
                        .HasColumnType("bit");

                    b.Property<bool>("CyberLiability")
                        .HasColumnType("bit");

                    b.Property<bool>("DeferredCompensation")
                        .HasColumnType("bit");

                    b.Property<bool>("DirectorsOfficersLiability")
                        .HasColumnType("bit");

                    b.Property<string>("FullTimeEmployees")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("GeneralLiability")
                        .HasColumnType("bit");

                    b.Property<bool>("GroupDisabilityInsurance")
                        .HasColumnType("bit");

                    b.Property<bool>("GroupHealthInsurance")
                        .HasColumnType("bit");

                    b.Property<bool>("GroupLifeInsurance")
                        .HasColumnType("bit");

                    b.Property<bool>("KeyManDisabilityInsurance")
                        .HasColumnType("bit");

                    b.Property<bool>("KeyManLifeInsurance")
                        .HasColumnType("bit");

                    b.Property<string>("LegalEntity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OneTimeOrSeasonal")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PartTimeEmployees")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PartnersOwners")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("ProfessionalLiability")
                        .HasColumnType("bit");

                    b.Property<string>("ReplaceExistingPolicy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("RetirementPlans")
                        .HasColumnType("bit");

                    b.Property<string>("SubContractors")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("SupplementalPlans")
                        .HasColumnType("bit");

                    b.Property<bool>("WorkersCompensation")
                        .HasColumnType("bit");

                    b.Property<string>("YearsInBusiness")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("QuoteId");

                    b.HasIndex("BusinessName")
                        .HasDatabaseName("IX_BusinessQuotes_BusinessName");

                    b.ToTable("BusinessQuotes");
                });

            modelBuilder.Entity("JecaInsurance.API.Models.Claim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("AdditionalComments")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ClaimNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IncidentDescription")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("InformationSecure")
                        .HasColumnType("bit");

                    b.Property<string>("InsuranceCarrier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("ClaimNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Claims_ClaimNumber");

                    b.HasIndex("ClaimType")
                        .HasDatabaseName("IX_Claims_ClaimType");

                    b.HasIndex("CreatedDate")
                        .HasDatabaseName("IX_Claims_CreatedDate");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_Claims_Email");

                    b.HasIndex("InsuranceCarrier")
                        .HasDatabaseName("IX_Claims_InsuranceCarrier");

                    b.HasIndex("PolicyNumber")
                        .HasDatabaseName("IX_Claims_PolicyNumber");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Claims_Status");

                    b.HasIndex("FirstName", "LastName")
                        .HasDatabaseName("IX_Claims_FirstName_LastName");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("JecaInsurance.API.Models.ClaimsIn3YearsOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("ClaimsIn3YearsOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Value = "None"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Value = "1"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Value = "2"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Value = "3"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Value = "4+"
                        });
                });

            modelBuilder.Entity("JecaInsurance.API.Models.Consultation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("AssignedAgent")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConsultationNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ConsultationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("DiscussionTopics")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("InformationSecure")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("AssignedAgent")
                        .HasDatabaseName("IX_Consultations_AssignedAgent");

                    b.HasIndex("CompletedDate")
                        .HasDatabaseName("IX_Consultations_CompletedDate");

                    b.HasIndex("ConsultationNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Consultations_ConsultationNumber");

                    b.HasIndex("ConsultationType")
                        .HasDatabaseName("IX_Consultations_ConsultationType");

                    b.HasIndex("CreatedDate")
                        .HasDatabaseName("IX_Consultations_CreatedDate");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_Consultations_Email");

                    b.HasIndex("ScheduledDate")
                        .HasDatabaseName("IX_Consultations_ScheduledDate");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Consultations_Status");

                    b.HasIndex("FirstName", "LastName")
                        .HasDatabaseName("IX_Consultations_FirstName_LastName");

                    b.ToTable("Consultations");
                });

            modelBuilder.Entity("JecaInsurance.API.Models.ContactMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("InquiryType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("ProcessedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProcessingNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("ContactNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_ContactMessages_ContactNumber");

                    b.HasIndex("CreatedDate")
                        .HasDatabaseName("IX_ContactMessages_CreatedDate");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_ContactMessages_Email");

                    b.HasIndex("InquiryType")
                        .HasDatabaseName("IX_ContactMessages_InquiryType");

                    b.HasIndex("ProcessedDate")
                        .HasDatabaseName("IX_ContactMessages_ProcessedDate");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_ContactMessages_Status");

                    b.HasIndex("FirstName", "LastName")
                        .HasDatabaseName("IX_ContactMessages_FirstName_LastName");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("JecaInsurance.API.Models.ContactUpdate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("ChangeDescription")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("InformationSecure")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("ProcessedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProcessingNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UpdateNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("ChangeType")
                        .HasDatabaseName("IX_ContactUpdates_ChangeType");

                    b.HasIndex("CreatedDate")
                        .HasDatabaseName("IX_ContactUpdates_CreatedDate");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_ContactUpdates_Email");

                    b.HasIndex("ProcessedDate")
                        .HasDatabaseName("IX_ContactUpdates_ProcessedDate");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_ContactUpdates_Status");

                    b.HasIndex("UpdateNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_ContactUpdates_UpdateNumber");

                    b.HasIndex("FirstName", "LastName")
                        .HasDatabaseName("IX_ContactUpdates_FirstName_LastName");

                    b.ToTable("ContactUpdates");
                });

            modelBuilder.Entity("JecaInsurance.API.Models.ContinuousCoverageOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("ContinuousCoverageOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Value = "3+ Years"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Value = "2 Years"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Value = "1 Year"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Value = "6 Months"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Value = "Under 6 months"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Value = "Not Currently Insured"
                        });
                });

            modelBuilder.Entity("JecaInsurance.API.Models.CoverageDesiredOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("CoverageDesiredOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Value = "State Minimum"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Value = "Standard Coverage"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Value = "Premium Coverage"
                        });
                });

            modelBuilder.Entity("JecaInsurance.API.Models.DentalQuote", b =>
                {
                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DentalRecords")
                        .HasColumnType("bit");

                    b.Property<bool>("InsuranceCards")
                        .HasColumnType("bit");

                    b.Property<string>("NumberOfPeople")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("PolicyStartDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TreatmentHistory")
                        .HasColumnType("bit");

                    b.Property<bool>("XrayImages")
                        .HasColumnType("bit");

                    b.HasKey("QuoteId");

                    b.ToTable("DentalQuotes");
                });

            modelBuilder.Entity("JecaInsurance.API.Models.DisabilityInsuranceQuote", b =>
                {
                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MonthlyIncome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("PolicyStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TobaccoUse")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("QuoteId");

                    b.ToTable("DisabilityInsuranceQuotes");
                });

            modelBuilder.Entity("JecaInsurance.API.Models.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("AccidentsTickets")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("DriverType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("Married")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DateOfBirth")
                        .HasDatabaseName("IX_Drivers_DateOfBirth");

                    b.HasIndex("DriverType")
                        .HasDatabaseName("IX_Drivers_DriverType");

                    b.HasIndex("QuoteId")
                        .HasDatabaseName("IX_Drivers_QuoteId");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("JecaInsurance.API.Models.FloodQuote", b =>
                {
                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BuildingPurpose")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DesiredBuilding")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DesiredContents")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FloodClaims")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HomeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PolicyOwner")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RentingHome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("QuoteId");

                    b.ToTable("FloodQuotes");
                });

            modelBuilder.Entity("JecaInsurance.API.Models.HealthQuote", b =>
                {
                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnnualHouseholdIncome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dependents")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pregnant")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Smoker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("SpouseDateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("SpouseFirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SpouseGender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SpouseLastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SpousePregnant")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SpouseSmoker")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("QuoteId");

                    b.ToTable("HealthQuotes");
                });

            modelBuilder.Entity("JecaInsurance.API.Models.HomeQuote", b =>
                {
                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bathrooms")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Bedrooms")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ConstructionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("CoveredDeckPatio")
                        .HasColumnType("bit");

                    b.Property<string>("CreditRating")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("DeadBolts")
                        .HasColumnType("bit");

                    b.Property<string>("DesiredDeductible")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DogBreeds")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FireAlarm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("FireExtinguishers")
                        .HasColumnType("bit");

                    b.Property<string>("FloodPlan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Foundation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GarageType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HomeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MunicipalLocation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PersonalLiability")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("PolicyStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PrimaryHeating")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReplaceExistingPolicy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReplacementCost")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReportedClaims")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RoofAge")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RoofType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SecuritySystem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SquareFootage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Stories")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("SwimmingPool")
                        .HasColumnType("bit");

                    b.Property<bool>("Trampoline")
                        .HasColumnType("bit");

                    b.Property<string>("YearBuilt")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("QuoteId");

                    b.HasIndex("PolicyStartDate")
                        .HasDatabaseName("IX_HomeQuotes_PolicyStartDate");

                    b.ToTable("HomeQuotes");
                });

            modelBuilder.Entity("JecaInsurance.API.Models.LandlordsQuote", b =>
                {
                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberOfUnits")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TotalSquareFeet")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("QuoteId");

                    b.ToTable("LandlordsQuotes");
                });

            modelBuilder.Entity("JecaInsurance.API.Models.LifeInsuranceQuote", b =>
                {
                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AmountOfCoverage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BusinessHobby")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CancerDiagnosis")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CoverageType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Height")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MajorDiseases")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("PolicyStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StrokeHeartAttack")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TobaccoUse")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Weight")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("QuoteId");

                    b.ToTable("LifeInsuranceQuotes");
                });

            modelBuilder.Entity("JecaInsurance.API.Models.MedicareAdvantageQuote", b =>
                {
                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PolicyStartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("QuoteId");

                    b.ToTable("MedicareAdvantageQuotes");
                });

            modelBuilder.Entity("JecaInsurance.API.Models.MedicareSupplementQuote", b =>
                {
                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PolicyStartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("QuoteId");

                    b.ToTable("MedicareSupplementQuotes");
                });

            modelBuilder.Entity("JecaInsurance.API.Models.MotorcycleQuote", b =>
                {
                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("QuoteId");

                    b.ToTable("MotorcycleQuotes");
                });

            modelBuilder.Entity("JecaInsurance.API.Models.PolicyExpiresInOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("PolicyExpiresInOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Value = "Not sure"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Value = "A Few days"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Value = "2 weeks"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Value = "1 Month"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Value = "2 Months"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Value = "3 Months"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            Value = "3-6 Months"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 8,
                            Value = "6+ Months"
                        });
                });

            modelBuilder.Entity("JecaInsurance.API.Models.PolicyReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("DiscussionTopics")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("InformationSecure")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ReviewMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReviewNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate")
                        .HasDatabaseName("IX_PolicyReviews_CreatedDate");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_PolicyReviews_Email");

                    b.HasIndex("ReviewMethod")
                        .HasDatabaseName("IX_PolicyReviews_ReviewMethod");

                    b.HasIndex("ReviewNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_PolicyReviews_ReviewNumber");

                    b.HasIndex("ScheduledDate")
                        .HasDatabaseName("IX_PolicyReviews_ScheduledDate");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_PolicyReviews_Status");

                    b.HasIndex("FirstName", "LastName")
                        .HasDatabaseName("IX_PolicyReviews_FirstName_LastName");

                    b.ToTable("PolicyReviews");
                });

            modelBuilder.Entity("JecaInsurance.API.Models.ProofOfInsurance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("DocumentPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("InformationSecure")
                        .HasColumnType("bit");

                    b.Property<string>("InsuranceCarrier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ProcessedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProcessingNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ProofType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RequestDescription")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("RequestNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate")
                        .HasDatabaseName("IX_ProofOfInsurances_CreatedDate");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_ProofOfInsurances_Email");

                    b.HasIndex("InsuranceCarrier")
                        .HasDatabaseName("IX_ProofOfInsurances_InsuranceCarrier");

                    b.HasIndex("PolicyNumber")
                        .HasDatabaseName("IX_ProofOfInsurances_PolicyNumber");

                    b.HasIndex("ProcessedDate")
                        .HasDatabaseName("IX_ProofOfInsurances_ProcessedDate");

                    b.HasIndex("ProofType")
                        .HasDatabaseName("IX_ProofOfInsurances_ProofType");

                    b.HasIndex("RequestNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_ProofOfInsurances_RequestNumber");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_ProofOfInsurances_Status");

                    b.HasIndex("FirstName", "LastName")
                        .HasDatabaseName("IX_ProofOfInsurances_FirstName_LastName");

                    b.ToTable("ProofOfInsurances");
                });

            modelBuilder.Entity("JecaInsurance.API.Models.Quote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("AdditionalComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ClaimsIn3Years")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ContinuousCoverage")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CoverageDesired")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("CurrentInsuranceCompany")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("InformationSecure")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PolicyExpiresIn")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("QuoteNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("QuoteType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TicketsIn3Years")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("WhenToStart")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate")
                        .HasDatabaseName("IX_Quotes_CreatedDate");

                    b.HasIndex("Email")
                        .HasDatabaseName("IX_Quotes_Email");

                    b.HasIndex("QuoteNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Quotes_QuoteNumber");

                    b.HasIndex("QuoteType")
                        .HasDatabaseName("IX_Quotes_QuoteType");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Quotes_Status");

                    b.HasIndex("FirstName", "LastName")
                        .HasDatabaseName("IX_Quotes_FirstName_LastName");

                    b.ToTable("Quotes");
                });

            modelBuilder.Entity("JecaInsurance.API.Models.RentersQuote", b =>
                {
                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CoveredDeckPatio")
                        .HasColumnType("bit");

                    b.Property<string>("CreditRating")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("DeadBolts")
                        .HasColumnType("bit");

                    b.Property<string>("DesiredDeductible")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DogBreeds")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EstimatedSquareFootage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("FireExtinguishers")
                        .HasColumnType("bit");

                    b.Property<string>("PersonalLiabilityCoverage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReplaceExistingPolicy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReplacementValue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReportedClaims")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("SwimmingPool")
                        .HasColumnType("bit");

                    b.Property<string>("TotalNumberOfRooms")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("Trampoline")
                        .HasColumnType("bit");

                    b.Property<string>("TypeOfHome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("QuoteId");

                    b.ToTable("RentersQuotes");
                });

            modelBuilder.Entity("JecaInsurance.API.Models.TicketsIn3YearsOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("TicketsIn3YearsOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Value = "None"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Value = "1"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Value = "2"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Value = "3"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Value = "4"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Value = "5"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            Value = "6+"
                        });
                });

            modelBuilder.Entity("JecaInsurance.API.Models.UmbrellaInsuranceQuote", b =>
                {
                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AmountOfCoverage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HouseholdAccidents")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("PolicyStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PropertiesOwned")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrafficTickets")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VehiclesOwned")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("QuoteId");

                    b.ToTable("UmbrellaInsuranceQuotes");
                });

            modelBuilder.Entity("JecaInsurance.API.Models.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("AnnualMileage")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BoatUse")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CollisionDeductible")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ComprehensiveDeductible")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Deductible")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DriveToWorkSchool")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("EngineType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HullMaterial")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IsLeased")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("Length")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MarketValue")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MoreThanTwoVehicles")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("NumberOfEngines")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StorageLocation")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StructuralModifications")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TotalHorsepower")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TrailerCoverage")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("WatercraftType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("WorkSchoolDistance")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("QuoteId")
                        .HasDatabaseName("IX_Vehicles_QuoteId");

                    b.HasIndex("VehicleType")
                        .HasDatabaseName("IX_Vehicles_VehicleType");

                    b.HasIndex("Year", "Make", "Model")
                        .HasDatabaseName("IX_Vehicles_Year_Make_Model");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("JecaInsurance.API.Models.VisionQuote", b =>
                {
                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NumberOfPeople")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("PolicyStartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("QuoteId");

                    b.ToTable("VisionQuotes");
                });

            modelBuilder.Entity("JecaInsurance.API.Models.WatercraftType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("WatercraftTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Value = "Runaboat"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Value = "Bass Boat"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Value = "Cabin Cruiser"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Value = "Pontoon"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Value = "Sail Boat - Single-Hull"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Value = "Sail Boat - Multi-Hull"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            Value = "Houseboat"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 8,
                            Value = "Inflatable"
                        });
                });

            modelBuilder.Entity("JecaInsurance.API.Models.WorkSchoolDistanceOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("WorkSchoolDistanceOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Value = "Less than 5 Miles"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Value = "5 Miles"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Value = "10 Miles"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Value = "15 Miles"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Value = "20 Miles"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Value = "30 Miles"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            Value = "Over 30 Miles"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 8,
                            Value = "N/A"
                        });
                });

            modelBuilder.Entity("JecaInsurance.API.Models.WorkersCompQuote", b =>
                {
                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NumberOfEmployees")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("QuoteId");

                    b.ToTable("WorkersCompQuotes");
                });

            modelBuilder.Entity("JecaInsurance.API.Models.AnnuityQuote", b =>
                {
                    b.HasOne("JecaInsurance.API.Models.Quote", "Quote")
                        .WithOne("AnnuityQuote")
                        .HasForeignKey("JecaInsurance.API.Models.AnnuityQuote", "QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("JecaInsurance.API.Models.AutoQuote", b =>
                {
                    b.HasOne("JecaInsurance.API.Models.Quote", "Quote")
                        .WithOne("AutoQuote")
                        .HasForeignKey("JecaInsurance.API.Models.AutoQuote", "QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("JecaInsurance.API.Models.BOPQuote", b =>
                {
                    b.HasOne("JecaInsurance.API.Models.Quote", "Quote")
                        .WithOne("BOPQuote")
                        .HasForeignKey("JecaInsurance.API.Models.BOPQuote", "QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("JecaInsurance.API.Models.BoatQuote", b =>
                {
                    b.HasOne("JecaInsurance.API.Models.Quote", "Quote")
                        .WithOne("BoatQuote")
                        .HasForeignKey("JecaInsurance.API.Models.BoatQuote", "QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("JecaInsurance.API.Models.BusinessQuote", b =>
                {
                    b.HasOne("JecaInsurance.API.Models.Quote", "Quote")
                        .WithOne("BusinessQuote")
                        .HasForeignKey("JecaInsurance.API.Models.BusinessQuote", "QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("JecaInsurance.API.Models.DentalQuote", b =>
                {
                    b.HasOne("JecaInsurance.API.Models.Quote", "Quote")
                        .WithOne("DentalQuote")
                        .HasForeignKey("JecaInsurance.API.Models.DentalQuote", "QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("JecaInsurance.API.Models.DisabilityInsuranceQuote", b =>
                {
                    b.HasOne("JecaInsurance.API.Models.Quote", "Quote")
                        .WithOne("DisabilityInsuranceQuote")
                        .HasForeignKey("JecaInsurance.API.Models.DisabilityInsuranceQuote", "QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("JecaInsurance.API.Models.Driver", b =>
                {
                    b.HasOne("JecaInsurance.API.Models.Quote", "Quote")
                        .WithMany("Drivers")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("JecaInsurance.API.Models.FloodQuote", b =>
                {
                    b.HasOne("JecaInsurance.API.Models.Quote", "Quote")
                        .WithOne("FloodQuote")
                        .HasForeignKey("JecaInsurance.API.Models.FloodQuote", "QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("JecaInsurance.API.Models.HealthQuote", b =>
                {
                    b.HasOne("JecaInsurance.API.Models.Quote", "Quote")
                        .WithOne("HealthQuote")
                        .HasForeignKey("JecaInsurance.API.Models.HealthQuote", "QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("JecaInsurance.API.Models.HomeQuote", b =>
                {
                    b.HasOne("JecaInsurance.API.Models.Quote", "Quote")
                        .WithOne("HomeQuote")
                        .HasForeignKey("JecaInsurance.API.Models.HomeQuote", "QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("JecaInsurance.API.Models.LandlordsQuote", b =>
                {
                    b.HasOne("JecaInsurance.API.Models.Quote", "Quote")
                        .WithOne("LandlordsQuote")
                        .HasForeignKey("JecaInsurance.API.Models.LandlordsQuote", "QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("JecaInsurance.API.Models.LifeInsuranceQuote", b =>
                {
                    b.HasOne("JecaInsurance.API.Models.Quote", "Quote")
                        .WithOne("LifeInsuranceQuote")
                        .HasForeignKey("JecaInsurance.API.Models.LifeInsuranceQuote", "QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("JecaInsurance.API.Models.MedicareAdvantageQuote", b =>
                {
                    b.HasOne("JecaInsurance.API.Models.Quote", "Quote")
                        .WithOne("MedicareAdvantageQuote")
                        .HasForeignKey("JecaInsurance.API.Models.MedicareAdvantageQuote", "QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("JecaInsurance.API.Models.MedicareSupplementQuote", b =>
                {
                    b.HasOne("JecaInsurance.API.Models.Quote", "Quote")
                        .WithOne("MedicareSupplementQuote")
                        .HasForeignKey("JecaInsurance.API.Models.MedicareSupplementQuote", "QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("JecaInsurance.API.Models.MotorcycleQuote", b =>
                {
                    b.HasOne("JecaInsurance.API.Models.Quote", "Quote")
                        .WithOne("MotorcycleQuote")
                        .HasForeignKey("JecaInsurance.API.Models.MotorcycleQuote", "QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("JecaInsurance.API.Models.RentersQuote", b =>
                {
                    b.HasOne("JecaInsurance.API.Models.Quote", "Quote")
                        .WithOne("RentersQuote")
                        .HasForeignKey("JecaInsurance.API.Models.RentersQuote", "QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("JecaInsurance.API.Models.UmbrellaInsuranceQuote", b =>
                {
                    b.HasOne("JecaInsurance.API.Models.Quote", "Quote")
                        .WithOne("UmbrellaInsuranceQuote")
                        .HasForeignKey("JecaInsurance.API.Models.UmbrellaInsuranceQuote", "QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("JecaInsurance.API.Models.Vehicle", b =>
                {
                    b.HasOne("JecaInsurance.API.Models.Quote", "Quote")
                        .WithMany("Vehicles")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("JecaInsurance.API.Models.VisionQuote", b =>
                {
                    b.HasOne("JecaInsurance.API.Models.Quote", "Quote")
                        .WithOne("VisionQuote")
                        .HasForeignKey("JecaInsurance.API.Models.VisionQuote", "QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("JecaInsurance.API.Models.WorkersCompQuote", b =>
                {
                    b.HasOne("JecaInsurance.API.Models.Quote", "Quote")
                        .WithOne("WorkersCompQuote")
                        .HasForeignKey("JecaInsurance.API.Models.WorkersCompQuote", "QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("JecaInsurance.API.Models.Quote", b =>
                {
                    b.Navigation("AnnuityQuote");

                    b.Navigation("AutoQuote");

                    b.Navigation("BOPQuote");

                    b.Navigation("BoatQuote");

                    b.Navigation("BusinessQuote");

                    b.Navigation("DentalQuote");

                    b.Navigation("DisabilityInsuranceQuote");

                    b.Navigation("Drivers");

                    b.Navigation("FloodQuote");

                    b.Navigation("HealthQuote");

                    b.Navigation("HomeQuote");

                    b.Navigation("LandlordsQuote");

                    b.Navigation("LifeInsuranceQuote");

                    b.Navigation("MedicareAdvantageQuote");

                    b.Navigation("MedicareSupplementQuote");

                    b.Navigation("MotorcycleQuote");

                    b.Navigation("RentersQuote");

                    b.Navigation("UmbrellaInsuranceQuote");

                    b.Navigation("Vehicles");

                    b.Navigation("VisionQuote");

                    b.Navigation("WorkersCompQuote");
                });
#pragma warning restore 612, 618
        }
    }
}
